Train:
  batch_size: 32
  learning_rate: 0.01
  reg: 0.0005
  epochs: 80
  steps: [6, 8]
  warmup: 0
  momentum: 0.9

network:
  model: MyModel # TwoLayerNet or VanillaCNN or MyModel or ResNet-32

data:
  imbalance: regular # regular or imbalance
  save_best: True

loss:
  loss_type: CE # CE or Focal
  reweight: True
  beta: 0.99 #between 0 and 1 